steps:
# Docker Build
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/website-flo-docker-repo/flo-website-image:latest', '.']
# Docker Push
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','us-central1-docker.pkg.dev/${PROJECT_ID}/website-flo-docker-repo/flo-website-image:latest']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'resume-server-2', '--image', 'us-central1-docker.pkg.dev/${PROJECT_ID}/website-flo-docker-repo/flo-website-image:latest', '--region', 'us-central1']
images:
- us-central1-docker.pkg.dev/${PROJECT_ID}/website-flo-docker-repo/flo-website-image:latest

